### ISSUE TITLE
None of these options set a forwarding delay, and specify keywords.

### ISSUE THREAD

**Issue by cnstephen** [MohammadShabib/Telegram-Forwarder-Bot#1]
? Enter source channel Stop
? Forward Type: Live
and no real time Forward
is none of set a forwarding delay？

**Comment by MohammadShabib** [comment]
Hi
yes I removed this feature recently and everything is forwarded immediately.
I can readd it if you want

**Comment by wademac** [comment]
I would love to have the keyword feature :)
