### ISSUE TITLE
Why is there a delay in forwarding information

### ISSUE THREAD

**Issue by cnstephen** [MohammadShabib/Telegram-Forwarder-Bot#2]
Why is there a delay in forwarding messages, ranging from tens of seconds to several minutes later than the source channel? Is it a monitoring or forwarding problem?

**Comment by MohammadShabib** [comment]
does the message have any files or images ?
If yes its probably related to your internet connection

**Comment by MohammadShabib** [comment]
from the logs you sent, 
there is a cool down period from Telegram side.
It happens when you send a lot of messages in a short period of time.
